name: integration-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0

    - name: test
      run: ./test.sh

    - name: 📧 Discord success notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
      uses: Ilshidur/action-discord@master
      with:
        args: '☑️ Integration test passed for branch `${{ github.ref }}`'

    - name: 📧 Discord failure notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
      uses: Ilshidur/action-discord@master
      with:
        args: '🚫 Integration test failed for branch `${{ github.ref }}`'
